/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"


int main(void)
{
	//bật xung hse
	RCC->CR |= RCC_CR_HSEON;
	while(!(RCC->CR & RCC_CR_HSERDY));
	//bật xung cho bus portc
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
	//cấu hình chân cho pc13
	GPIOC->CRH |= GPIO_CRH_MODE14;
	GPIOC->CRH &=~GPIO_CRH_CNF14_0;

	uint8_t a=0;
	//đẩy data 1 ra pc13
	GPIOC->ODR |=GPIO_ODR_ODR14;
	a=a+1;
	//đẩy data 0 ra pc13
	GPIOC->ODR &=~GPIO_ODR_ODR14;
	a=a+1;
	GPIOC->ODR |=GPIO_ODR_ODR14;
	a=a+1;
	GPIOC->ODR &=~GPIO_ODR_ODR14;
	a=a+1;
}
